#ifndef VITROIO_SDK_CANBUS_PROTOCOL_CONSTS_H
#define VITROIO_SDK_CANBUS_PROTOCOL_CONSTS_H

#define VITROIO_CANBUS_PROTOCOL_NODE_ID_OFFSET 11
#define VITROIO_CANBUS_PROTOCOL_NODE_ID_MASK 0x1FFFF800
#define VITROIO_CANBUS_PROTOCOL_PARAM_ID_OFFSET 0
#define VITROIO_CANBUS_PROTOCOL_PARAM_ID_MASK 0x7FF

#define VITROIO_CANBUS_PROTOCOL_BROADCAST_NODE_ID 0

#define VITROIO_RESERVED_PARAMID_UPPER_LIMIT 0x700
#define VITROIO_RESERVED_PARAMID_LOWER_LIMIT 0x100


#define VITROIO_PROTOCOL_NODE_ID_RES_PARAMID               0x00
#define VITROIO_PROTOCOL_NODE_ID_REQ_PARAMID               0x0A
#define VITROIO_PROTOCOL_UPG_REG_A_PARAMID                 0x10
#define VITROIO_PROTOCOL_UPG_REG_B_PARAMID                 0x20
#define VITROIO_PROTOCOL_FW_VER_PARAMID                    0x30
#define VITROIO_PROTOCOL_PROVISIONING_SINGLE_REQ_PARAMID   0x49
#define VITROIO_PROTOCOL_PROVISIONING_REQ_PARAMID          0x50
#define VITROIO_PROTOCOL_PROVISIONING_RESP_PARAMID         0x51
#define VITROIO_PROTOCOL_EXTERNAL_FRAME                    0x60

#define START_FRAME_PARAMETER_ID 0x7FF
#define TIMESTAMP_REQUEST_PARAMETER_ID 0x40


#endif // VITROIO_SDK_CANBUS_PROTOCOL_CONSTS_H